- set_fact:
    lxc_pkgname: "python3-lxc"
  when: ansible_os_family == "Debian" and ansible_distribution_major_version | int >= 11

- set_fact:
    lxc_pkgname: "python-lxc"
  when: ansible_os_family == "Debian" and ansible_distribution_major_version | int < 11

- name: Install packages
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: latest
  when: ansible_distribution_major_version == "9"

- name: Install packages
  become: yes
  apt:
    name:
      - openssh-server
      - cryptsetup
      - build-essential
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - linux-source
      - dkms
      - nfs-common
      - perl
      - libnl-genl-3-dev
      - libunwind-dev
      - libelf-dev
      - elfutils
      - pkg-config
      - time
      - nano
      - valgrind
      - curl
      - rsync
      - git
      - python3
      - python3-pip
      - python3-setuptools
      - python3-dev
      - python3-venv
      - xz-utils
      - tcpdump
      - g++
      - unzip
      - nmap
      - tcpdump
      - iproute2
      - lxc
      - lxc-dev
      - "{{ lxc_pkgname }}"
    state: latest
    update_cache: yes


- name: Install lxc-templates
  become: yes
  apt:
    name:
      - lxc-templates
    state: latest
    update_cache: yes
  when: ansible_distribution_major_version|int > 9

- include_role:
    name: packages
    tasks_from: awscli
