---
- hosts: localhost
  gather_facts: true
  become: yes
  vars:
    docker_api: 'http'

  roles:
    - role: auth
    - role: common

  tasks:
    - include_role:
        name: packages
        tasks_from: redhat

    - name: Install gcc-plugin-devel
      shell: "yum --enablerepo ol8_codeready_builder install -y gcc-plugin-devel"
    
    - include_role:
        name: general
        tasks_from: redhat
