---
- hosts: localhost
  gather_facts: true
  become: yes

  roles:
    - role: auth
    - role: common

  tasks:
    - include_role:
        name: packages
        tasks_from: debian

    - name: Install gcc-xx-plugin-dev
      shell: "apt-get install -y gcc-11-plugin-dev"

    - include_role:
        name: general
        tasks_from: debian
